### ISSUE TITLE
Ulid's performance is much lower than nuid's performance

### ISSUE THREAD

**Issue by baoyachi** [imbolc/tower-request-id#2]
I noticed that the tower-request-id library uses [ULID](https://crates.io/crates/ulid) as a generation rule for generating unique request IDs, but when I compared it with the following two libraries, the performance difference was quite significant.

* https://crates.io/crates/nuid
* https://crates.io/crates/ulid

* the rust code in main.rs file
```rust
use std::time::Instant;
use ulid::Ulid;

fn main() {
    let now = Instant::now();
    for i in 0..1000_000_000 {
        let _ = Ulid::new();
    }
    println!("{:?}", now.elapsed());


    let now = Instant::now();
    for i in 0..1000_000_000 {
        let _ = nuid::next();
    }
    println!("{:?}", now.elapsed());
}
```

* toml file
```toml
[package]
name = "test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ulid = "1"
nuid = "0.4.1"
```

* exec output
```bash
37.469178958s
25.318614166s
```

* env
```bash
ProductName:		macOS
ProductVersion:		13.3.1
ProductVersionExtra:	(a)
BuildVersion:		22E772610a

```
